name: Syntax and lint check
run-name: ${{ github.actor }} is commiting to PR ${{ github.ref }}
on:
  pull_request:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - id: syntax
        run: terraform fmt -recursive -check
